version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: seat_reservation_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seat_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - seat_reservation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: seat_reservation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - seat_reservation_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: seat_reservation_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - seat_reservation_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  seat_reservation_network:
    driver: bridge